//Names for LEDs and their states
#define DOOR_OPEN_LED 1
#define WRITE_PROTECT_LED 2
#define CARD_DETECT_LED 3
#define ANT_A_ACTIVE_LED 4
#define ANT_B_ACTIVE_LED 5
//#define MSG_STATUS_LED 6
#define USB_STATUS_LED 7
#define COM_STATUS_LED 8
#define STINGER_TX_STATUS_LED 9
#define STINGER_GENERIC_STATUS_LED 10
#define SD_ERROR_LED 11
#define TRANSMITTER_STATUS_LED 12
#define RECORD_STATUS_LED 13
#define STREC_PLAY_STATUS_LED 14
#define STREC_LIVE_STATUS_LED 15
#define STREC_RECORD_STATUS_LED 16
#define STREC_PLAYBACK_STATUS_LED 17
#define REC_STATUS_LED 18
#define REC_CARD_PRESENT_LED 19
#define REC_USB_PRESENT_LED 20

/*
#define LOCK_MONO_FS_NOSQ_FREQ1_LED 11
#define LOCK_MONO_FS_NOSQ_FREQ2_LED 12
#define LOCK_MONO_FS_NOSQ_FREQ3_LED 13
#define LOCK_MONO_FS_NOSQ_FREQ4_LED 14
#define LOCK_MONO_FS_NOSQ_FREQ5_LED 15
#define LOCK_MONO_FS_NOSQ_FREQ6_LED 16
#define LOCK_MONO_FS_NOSQ_FREQ7_LED 17
#define LOCK_MONO_FS_NOSQ_FREQ8_LED 18

#define LOCK_STEREO_FS_NOSQ_FREQ1_LED 21
#define LOCK_STEREO_FS_NOSQ_FREQ2_LED 22
#define LOCK_STEREO_FS_NOSQ_FREQ3_LED 23
#define LOCK_STEREO_FS_NOSQ_FREQ4_LED 24
#define LOCK_STEREO_FS_NOSQ_FREQ5_LED 25
#define LOCK_STEREO_FS_NOSQ_FREQ6_LED 26
#define LOCK_STEREO_FS_NOSQ_FREQ7_LED 27
#define LOCK_STEREO_FS_NOSQ_FREQ8_LED 28

#define LOCK_MONO_FS_FREQ1_LED 31
#define LOCK_MONO_FS_FREQ2_LED 32
#define LOCK_MONO_FS_FREQ3_LED 33
#define LOCK_MONO_FS_FREQ4_LED 34
#define LOCK_MONO_FS_FREQ5_LED 35
#define LOCK_MONO_FS_FREQ6_LED 36
#define LOCK_MONO_FS_FREQ7_LED 37
#define LOCK_MONO_FS_FREQ8_LED 38

#define LOCK_STEREO_FS_FREQ1_LED 41
#define LOCK_STEREO_FS_FREQ2_LED 42
#define LOCK_STEREO_FS_FREQ3_LED 43
#define LOCK_STEREO_FS_FREQ4_LED 44
#define LOCK_STEREO_FS_FREQ5_LED 45
#define LOCK_STEREO_FS_FREQ6_LED 46
#define LOCK_STEREO_FS_FREQ7_LED 47
#define LOCK_STEREO_FS_FREQ8_LED 48

#define LOCK_MONO_FEC_FREQ1_LED 51
#define LOCK_MONO_FEC_FREQ2_LED 52
#define LOCK_MONO_FEC_FREQ3_LED 53
#define LOCK_MONO_FEC_FREQ4_LED 54
#define LOCK_MONO_FEC_FREQ5_LED 55
#define LOCK_MONO_FEC_FREQ6_LED 56
#define LOCK_MONO_FEC_FREQ7_LED 57
#define LOCK_MONO_FEC_FREQ8_LED 58
*/
#define LOCK_FREQ1_LED 61
#define LOCK_FREQ2_LED 62
#define LOCK_FREQ3_LED 63
#define LOCK_FREQ4_LED 64
#define LOCK_FREQ5_LED 65
#define LOCK_FREQ6_LED 66
#define LOCK_FREQ7_LED 67
#define LOCK_FREQ8_LED 68

#define LED_BLACK 1
#define LED_DARK_RED 2
#define LED_BRIGHT_RED 3
#define LED_GREEN 4
#define LED_YELLOW 5
#define LED_DARK_GREEN 6
#define LED_ORANGE 7


//Location of SD LEDs group
#define LED_SD_GROUP_XORIGIN 692
#define LED_SD_GROUP_YORIGIN 125
#define LED_SD_GROUP_YSPACING 23

//Location of Antenna Active LEDs group
#define LED_ANT_GROUP_XORIGIN 620
#define LED_ANT_GROUP_YORIGIN 173
#define LED_ANT_GROUP_YSPACING 55

//Location of USB LED
#define LED_USB_GROUP_XORIGIN 368
#define LED_USB_GROUP_YORIGIN 648

//Location of COM LED
#define LED_COM_GROUP_XORIGIN 280
#define LED_COM_GROUP_YORIGIN 380

//Location of Channels LEDs group
#define LED_CHAN_GROUP_XORIGIN 88
#define LED_CHAN_GROUP_YORIGIN 73
#define LED_CHAN_GROUP_XSPACING 36
#define LED_CHAN_GROUP_YSPACING 35

//Location of Tx Stinger status LED on Main screen
#define LED_TX_STINGER_XORIGIN 766
#define LED_TX_STINGER_YORIGIN 350

//Location of Generic Stinger status LED on Stinger screen
#define LED_GENERIC_STINGER_XORIGIN 105
#define LED_GENERIC_STINGER_YORIGIN 295

//Location of Transmitter status LED on Main screen
#define LED_TRANSMITTER_STATUS_XORIGIN 379
#define LED_TRANSMITTER_STATUS_YORIGIN 375

