//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by infinity.rc
//
#define ID_TIMER_CONTINUOUS             1
#define ID_TIMER_CHANNELS               2
#define ID_TIMER_SCAN                   3
#define ID_TIMER_STINGER_GENERIC        5
#define ID_TIMER_DEBUG_SDRAM_AUDIO      6
#define ID_TIMER_DOGLEASH_TIMEREMAIN    7
#define ID_TIMER_TIMECLOCKUPDATE        8
#define ID_TIMER_STINGER_RECORD         9
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_STINGERRECWIN               102
#define IDS_ABOUTBOX                    103
#define IDD_MAIN_DIALOG                 104
#define IDS_BITMAP                      105
#define IDD_SYSCLK_WIN                  109
#define IDD_EDITFILENAMEWIN             110
#define IDD_AUDIOSETUPWIN               111
#define IDR_MAINFRAME                   129
#define IDR_MENU1                       130
#define IDD_SCANWINDOW                  131
#define IDD_PLAYBACKWINDOW              132
#define IDD_STINGERWINDOW               133
#define IDD_ENTERPASSWORDWIN            134
#define IDB_BITMAP1                     135
#define IDB_BITMAP2                     136
#define IDI_USBBAD                      137
#define IDI_USBGOOD                     138
#define IDB_BITMAP3                     139
#define IDD_PASSWORDWIN                 140
#define IDD_SPECIALSTINGERCMDWIN        141
#define IDD_STEALTHRECSPECIALWIN        142
#define IDD_DOGLEASHWIN                 143
#define IDR_MENU2                       144
#define IDR_PASSWORDWINMENU             145
#define IDR_PASSWORDWIN                 146
#define IDD_CHANGEPASSWORDWIN           147
#define IDB_BITMAP4                     150
#define IDD_DEBUGWINDOW                 151
#define IDD_DEBUGAGCWINDOW              152
#define IDD_DIALOG1                     153
#define IDD_CHANNELSWINDOW              154
#define IDD_SETTINGS_COM                155
#define IDD_SETTINGS_MISC               156
#define ID_SETTINGS_ABOUT               157
#define IDI_ICON1                       158
#define ID_PLAY_AUDIO                   159
#define ID_SETTINGS_AUDIO               160
#define IDC_STEALTHREC_SOURCE_MIC       161
#define IDC_STEALTHREC_SOURCE_AUX       162
#define IDC_STEALTHREC_SOURCE_LINE      163
#define IDC_CONTINUOUS                  1001
#define IDC_cboByteToSend0              1002
#define IDC_CONTINUOUS2                 1004
#define IDC_UPDATE                      1005
#define IDC_PRINT_MSGS                  1006
#define IDC_BytesToSend1                1007
#define IDC_cboByteToSend1              1008
#define IDC_AutoIncrement               1009
#define IDC_Results                     1010
#define IDC_VOLTAGE_READOUT_TEXT        1011
#define IDC_SDMEMUSED                   1012
#define IDC_SDMEMTOTAL                  1013
#define IDC_TIME_REMAIN                 1014
#define IDC_DEBUG_MSG_MAIN              1015
#define IDC_TIME_USED                   1016
#define IDC_SD_ERROR_TEXT               1017
#define IDC_REC_FILE_NUM_TEXT           1018
#define IDC_FILENAME                    1019
#define IDC_ANT_B_TEXT                  1020
#define IDC_ANT_A_TEXT                  1021
#define IDC_txtVendorID                 1022
#define IDC_ANT_B_TEXT2                 1023
#define IDC_RAW_SUBCH_BYTES             1024
#define IDC_SERIAL_NUM                  1027
#define IDC_TXID                        1028
#define IDC_TXID3                       1029
#define IDC_TXVOLTAGE                   1031
#define IDC_RECEIVER_VOLTAGE            1032
#define IDC_TXID2                       1033
#define IDC_SERIAL_NUM2                 1034
#define IDC_RECEIVER_FIRMWARE_VERSION   1035
#define IDC_RECEIVER_FIRMWARE_VERSION2  1036
#define IDC_SERIAL_NUMBER               1037
#define IDC_RightAudio                  1038
#define IDC_LeftAudio                   1039
#define IDC_AntennaA                    1040
#define IDC_AntennaB                    1041
#define IDC_FilterSelect                1042
#define IDC_RAMMemUsedBargraph          1043
#define IDC_SDMemUsedBargraph           1044
#define IDC_RADIO1                      1045
#define IDC_FreqSelect                  1046
#define IDC_RADIO2                      1047
#define IDC_NoMute                      1048
#define IDC_HdPhone                     1049
#define IDC_AnalogHdPhone               1050
#define IDC_CALTONE_ON                  1051
#define IDC_CALTONE_NOLOCK              1052
#define IDC_CALTONE_OFF                 1053
#define IDC_RADIO10                     1054
#define IDC_SetFreq                     1055
#define IDC_FREQ_VAL_TEXT               1056
#define IDC_LoadFreqs                   1057
#define IDC_SaveFreqs                   1058
#define IDC_Filt400HzVerySharp          1059
#define IDC_Filt400HzSharp              1060
#define IDC_Filt200HzVerySharp          1061
#define IDC_Filt200HzSharp              1062
#define IDC_Filt200Hz                   1063
#define IDC_Filt100Hz                   1064
#define IDC_FiltFlat                    1065
#define IDC_FMTRANSMITFREQ              1066
#define IDC_FreqVal1                    1067
#define IDC_FreqVal2                    1068
#define IDC_FreqVal3                    1069
#define IDC_FreqVal4                    1070
#define IDC_FreqVal5                    1071
#define IDC_FreqVal6                    1072
#define IDC_FreqVal7                    1073
#define IDC_FreqVal8                    1074
#define IDC_STINGER_ON                  1075
#define IDC_STINGER_OFF                 1076
#define IDC_POWER                       1077
#define ID_SCAN                         1078
#define IDC_STINGER_OFF2                1079
#define IDC_STINGER_ALLOFF              1080
#define IDC_PLAYBACK_START              1081
#define IDC_TIMESTRING                  1082
#define IDC_DATESTRING                  1083
#define ID_CLEARSCAN                    1084
#define IDC_PLAYBACK_STOP               1085
#define IDC_MSG_SENT_COUNT              1086
#define IDC_TXSETFREQ                   1087
#define IDC_EDITFILENAME                1088
#define IDC_STEREO1                     1089
#define IDC_USE_COM                     1090
#define IDC_PREEMPHASIS                 1091
#define IDC_AGC_REMOTE                  1092
#define IDC_CHANLOCK1                   1093
#define IDC_PLAYBACK_MESSAGE            1094
#define IDC_MSG_SENT_COUNT2             1095
#define IDC_PLAY_AUDIO                  1096
#define IDC_ST_MSG_RCVD_COUNT           1097
#define IDC_USE_USB                     1098
#define IDC_PLAYBACKMODESTRING          1099
#define IDC_ANC_REMOTE                  1100
#define IDC_SWAP_LR                     1101
#define IDC_MONO_ON                     1102
#define IDC_STEALTHRECINFO              1103
#define IDC_STEALTH_REC_MODE_CAL        1104
#define IDC_STEALTHREC_SEND             1105
#define IDC_STEALTHREC_RECORD           1106
#define IDC_STEALTHREC_STOP             1107
#define IDC_STEALTHREC_PLAY             1108
#define IDC_DECLICK                     1109
#define IDC_RECORDMODE                  1110
#define IDC_STINGER_CMD                 1111
#define IDC_TRANSMITTER_FM              1112
#define IDC_TRANSMITTER_FMENC           1113
#define IDC_TRANSMITTER_DST             1114
#define IDC_OVERWRITEWHENFULL           1115
#define IDC_CHANNELSWINBUTTON           1116
#define IDC_MSG_SLIPS                   1117
#define IDC_CHANLOCK4                   1118
#define IDC_DOGLEASH_CMD_TEXT           1119
#define IDC_STEALTHREC_REWIND           1120
#define IDC_STEALTHREC_FF2END           1121
#define IDC_STEALTHREC_QUAL_128KBPS     1122
#define IDC_STEALTHREC_QUAL_96KBPS      1123
#define IDC_STEALTHREC_QUAL_64KBPS      1124
#define IDC_STEALTHREC_QUAL_32KBPS      1125
#define IDC_STEALTHREC_MODE_STEREO      1126
#define IDC_STEALTHREC_MODE_MONO        1127
#define IDC_DOGLEASH_TIMEREMAIN         1128
#define IDC_RSSI_LEFTLABEL              1129
#define IDC_RSSI_RIGHTLABEL             1130
#define IDC_DOGLEASH_ERASE              1131
#define IDC_CHANNELS_LEVEL1             1136
#define IDC_CHANNELS_LEVEL2             1137
#define IDC_CHANNELS_LEVEL3             1138
#define IDC_CHANNELS_LEVEL4             1139
#define IDC_CHANNELS_LEVEL5             1140
#define IDC_CHANNELS_LEVEL6             1141
#define IDC_CHANNELS_LEVEL7             1142
#define IDC_CHANNELS_LEVEL8             1143
#define ID_CHANNELSCLOSE                1145
#define ID_SCANCLOSE                    1146
#define IDC_FREQ_LABEL1                 1147
#define IDC_TUNE_FREQ_TEXT              1148
#define IDC_BAND_SW1                    1149
#define IDC_BAND_SW0                    1150
#define IDC_SLIDER1                     1151
#define IDC_SQUELCH_OFF                 1152
#define IDC_SQUELCH_ON                  1153
#define IDC_UPDATE_CUSTOMERID           1154
#define IDC_AUTO_ON_ENABLE              1155
#define IDC_DOGLEASH_ENABLE             1156
#define IDC_STINGER_REC_CMD_TEXT        1158
#define IDC_SDRAM_AUDIO                 1161
#define IDC_STINGER_REC_ERASEALL        1162
#define IDC_MONTHCALENDAR1              1163
#define IDC_SCAN_FREQ_TEXT              1164
#define IDC_SYS_CLK_UPDATE              1165
#define IDC_STINGER_ADDRESS_ENTER       1166
#define IDC_MIN_FREQ                    1167
#define IDC_MEMUSEDTEXT                 1168
#define IDC_PLAYBACKTIME                1169
#define IDC_MAX_FREQ                    1170
#define IDC_PLAYBACK_MSG                1171
#define IDC_PLAYBACK_TIME               1172
#define IDC_DATETIMEPICKER1             1173
#define IDC_RECEIVER_SD_CARD_SECTION    1174
#define IDC_CARD_PRESENT_MSG            1175
#define IDC_SYS_CLK_SET                 1176
#define IDC_RAM_USED_TEXT               1177
#define IDC_RECORD_STATUS_MSG           1178
#define IDC_SYS_CLK_SET_WINTIME         1179
#define IDC_MBYTES_OF                   1180
#define IDC_MBYTES_TOTAL                1181
#define IDC_TIME_REMAIN_TEXT            1182
#define IDC_TIME_USED_TEXT              1183
#define IDC_NEXT_SD_FILENAME_TEXT       1184
#define IDC_SDERROR_MSG                 1185
#define IDC_START_FREQ_TEXT             1186
#define IDC_MESSAGE_TEXT                1187
#define IDC_STOP_FREQ_TEXT              1188
#define IDC_PLAYBACK_MODE_TEXT          1189
#define IDC_DISPLAYMSGS                 1190
#define IDC_PLAYBACK_TIME_TEXT          1191
#define IDC_FREQ_PER_DIV_TEXT           1192
#define IDC_PRESS_STOP_TEXT             1193
#define IDC_AGC_LOCAL                   1194
#define IDC_FREQ_PER_DIV_TEXT2          1195
#define IDC_SPEC_SUBTITLE               1196
#define IDC_STEALTHREC_STARTDATE        1197
#define ID_PLAYBACKCLOSE                1198
#define IDC_STEALTHREC_STARTTIME        1199
#define IDC_RECEIVER_SD_CARD_SECTION2   1200
#define ID_PLAYBACKSTART                1201
#define IDC_STEALTHREC_REPEAT           1202
#define ID_PLAYBACKSTOP                 1203
#define IDC_RECORDER_MSG                1204
#define IDC_LOCALRECORDBUTTON           1205
#define IDC_SCANWINBUTTON               1206
#define IDC_CARD_PRESENT_MSG3           1207
#define IDC_RECORDER_CARD_PRESENT       1208
#define IDC_START_FREQ                  1209
#define IDC_RECORDER_USB_PRESENT        1210
#define IDC_CHANLOCK6                   1211
#define IDC_TXMT_MSG                    1212
#define IDC_CHANLOCK7                   1213
#define IDC_STOP_FREQ                   1214
#define IDC_STEP_FREQ                   1215
#define IDC_CHANLOCK8                   1216
#define IDC_RSSICHAN1                   1217
#define IDC_BEVEL_1                     1218
#define IDC_EDIT7                       1219
#define IDC_RSSICHAN2                   1220
#define IDC_SCANAREA                    1221
#define IDC_SCANAREA2                   1222
#define IDCHANNELSOK                    1223
#define IDC_RSSICHAN3                   1224
#define IDC_COMBO1                      1225
#define IDC_STINGER_ADDRESS2            1226
#define IDC_RSSICHAN4                   1227
#define IDC_COMBO2                      1228
#define IDC_RSSICHAN5                   1229
#define IDC_COMBO3                      1230
#define IDC_RSSICHAN6                   1231
#define IDC_RSSICHAN7                   1232
#define IDPW_FreqVal1                   1233
#define IDPW_FreqVal2                   1234
#define IDPW_FreqVal3                   1235
#define IDPW_FreqVal4                   1236
#define IDPW_FreqVal5                   1237
#define IDPW_FreqVal6                   1238
#define IDPW_FreqVal7                   1239
#define IDPW_FreqVal8                   1240
#define IDPW_FreqSelect                 1241
#define IDPW_FREQ_VAL_TEXT              1242
#define IDPW_SetFreq                    1243
#define IDPW_LoadFreqs                  1244
#define IDPW_SaveFreqs                  1245
#define IDPW_ENCWRD1                    1250
#define IDPW_ENCWRD2                    1251
#define IDPW_ENCWRD3                    1252
#define IDPW_ENCWRD4                    1253
#define IDPW_PROCESS                    1255
#define IDPW_LOAD                       1260
#define IDPW_SETCLOCK                   1265
#define IDPW_RESTORE_STATE              1266
#define IDPW_SENDSTINGERCMD             1267
#define IDPW_SPECIAL_STINGER_COMMAND    1268
#define ID_STEALTHREC_CLEARLOG          1269
#define ID_STEALTHREC_GET_VOLUME        1270
#define ID_STEALTHREC_GET_WORK_STATUS   1271
#define ID_STEALTHREC_GET_NUM_FILES     1272
#define ID_STEALTHREC_GET_SOUND_FILE    1273
#define ID_STEALTHREC_GET_CONN_STATUS   1274
#define ID_STEALTHREC_GET_SPACE         1275
#define ID_STEALTHREC_DELETEFILE        1276
#define ID_STEALTHREC_FASTFWD           1277
#define ID_STEALTHREC_FASTFWD2          1278
#define ID_STEALTHREC_FASTBKWD          1279
#define IDC_WASP_OFF_BUTTON             1300
#define IDC_WASP_ON_BUTTON              1301
#define IDC_WASP_ON_RADIOBUTTON         1302
#define IDC_WASP_OFF_RADIOBUTTON        1303
#define IDC_WASP_OFF_LINE1              1310
#define IDC_WASP_ON_LINE1               1311
#define IDC_WASP_OFF_LINE2              1312
#define IDC_WASP_ON_LINE2               1313
#define IDC_WASP_OFF_LINE3              1314
#define IDC_WASP_ON_LINE3               1315
#define IDC_WASP_OFF_LINE4              1316
#define IDC_WASP_ON_LINE4               1317
#define IDC_WASP_OFF_LINE5              1318
#define IDC_WASP_ON_LINE5               1319
#define IDC_WASP_OFF_LINE6              1320
#define IDC_WASP_OFF_LINE7              1321
#define IDC_WASP_ON_LINE7               1322
#define IDC_WASP_ON_LINE6               1323
#define IDC_WASP_SET_SYSTEM_CLK         1350
#define IDC_WASP_AUTO_ON_DELAY_HRS_MINS 1360
#define IDC_WASP_AUTO_ON_PERIOD         1361
#define IDC_WASP_AUTO_ON_REPEAT_HRS_MINS 1362
#define IDC_WASP_DOGLEASH_DAYS          1363
#define IDC_WASP_DOGLEASH_HRS_MINS      1364
#define IDC_WASP_AUTO_ON_DELAY_DAYS     1365
#define IDC_WASP_AUTO_ON_REPEAT_DAYS    1366
#define IDC_STINGER_VIEWREC             1380
#define IDC_WASP_DOGLEASH_VIEW          1381
#define IDC_WASP_RECORD                 1382
#define IDC_WASP_ADDRESS_DELETE         1425
#define IDC_WASP_ADDRESS_DELETEALL      1426
#define IDC_SPPADDR                     1427
#define IDC_SPPDATA                     1428
#define IDC_SPPWRITE                    1429
#define IDC_EEPROM_PIC1_ADDR            1430
#define IDC_DEVIATION                   1431
#define IDC_SPPREAD                     1432
#define IDC_BER                         1433
#define IDC_DEVIATIONWRITE              1434
#define IDC_DEVIATIONREAD               1435
#define IDC_BERREAD                     1436
#define IDC_OSC1_CONTROL1               1437
#define IDC_CENTERFREQ                  1438
#define IDC_OSC1_CONTROL2               1439
#define IDC_CENTERFREQWRITE             1440
#define IDC_CENTERFREQREAD              1441
#define IDC_DELTAPHASE                  1442
#define IDC_DELTAPHASEWRITE             1443
#define IDC_DELTAPHASEREAD4             1444
#define IDC_CLOCKSPERFS                 1445
#define IDC_CLKSPERFSWRITE              1446
#define IDC_CLKSPERFSREAD               1447
#define IDC_OSC1_CONTROL3               1448
#define IDC_OSC2_CONTROL1               1449
#define IDC_OSC2_CONTROL2               1450
#define IDC_OSC2_CONTROL3               1451
#define IDC_OSC1_NCOUNT1                1452
#define IDC_OSC1_NCOUNT2                1453
#define IDC_OSC1_NCOUNT3                1454
#define IDC_OSC2_NCOUNT1                1455
#define IDC_OSC2_NCOUNT2                1456
#define IDC_OSC2_NCOUNT3                1457
#define IDC_OSC1_RCOUNT1                1458
#define IDC_OSC1_RCOUNT2                1459
#define IDC_OSC1_RCOUNT3                1460
#define IDC_OSC2_RCOUNT1                1461
#define IDC_OSC2_RCOUNT2                1462
#define IDC_OSC2_RCOUNT3                1463
#define IDC_OSCCONTROLWRITE             1464
#define IDC_OSCCONTROLREAD              1465
#define IDC_RESET                       1466
#define IDC_UPDATE_BANDSW               1467
#define IDC_READ_SQUELCH                1468
#define IDC_WRITE_SQUELCH               1469
#define IDC_LOCAL_AGC_THRESHOLD         1470
#define IDC_EEPROM_PIC1_DATA            1471
#define IDC_EEPROM_PIC1_WRITE           1472
#define IDC_EEPROM_PIC1_READ            1473
#define IDC_SQUELCH_VALUE_TXT           1477
#define IDC_STINGER_CUSTOMERID          1478
#define IDC_LOCAL_AGC_WRITE             1479
#define IDC_SQUELCH_OFF_VALUE_TXT       1480
#define IDC_DEBUG_AGC_WIN2              1481
#define IDC_LOCAL_AGC_READ              1482
#define IDC_HYSTER_VALUE_TXT            1483
#define IDC_REMOTE_AGC_THRESHOLD        1484
#define IDC_HYSTER_OFF_VALUE_TXT        1485
#define IDC_REMOTE_AGC_WRITE            1486
#define IDC_REMOTE_AGC_READ             1487
#define IDC_LOCAL_AGC_ATTACK            1488
#define IDC_LOCAL_AGC_DECAY             1489
#define IDC_LOCAL_AGC_MAXGAIN           1490
#define IDC_REMOTE_AGC_ATTACK           1491
#define IDC_REMOTE_AGC_DECAY            1492
#define IDC_REMOTE_AGC_MAXGAIN          1493
#define IDC_AUTO_ON_TIME                1508
#define IDC_AUTO_ON_DATE                1509
#define IDC_RADIO5                      1516
#define IDC_RADIO6                      1517
#define IDC_RADIO7                      1518
#define IDC_RADIO8                      1519
#define IDC_LIST1                       1520
#define IDC_USB_STATUS                  1521
#define IDC_BUTTON5                     1522
#define IDC_TX_POWER                    1523
#define IDC_SET_CLOCK_MAIN              1524
#define IDC_TX_RESTORE_DEFAULT          1525
#define IDC_NEWAREA                     1526
#define IDC_RESYNCMSGS                  1600
#define IDC_STINGERBUTTON3              1620
#define IDC_DRAWLINES                   1640
#define IDC_COMBO18                     1670
#define IDC_CTL_TX_PWR_LOW              1672
#define IDC_CTL_TX_PWR_HI               1673
#define IDC_SLEEPER2_PWR_LOW            1674
#define IDC_SLEEPER2_PWR_HI             1675
#define IDC_CTRL_TX_STEREO              1676
#define IDC_CTRL_TX_MONO_L              1677
#define IDC_CTRL_TX_MONO_R              1678
#define IDC_OFF_STATE                   1679
#define IDC_OFF_STATE2                  1680
#define IDC_ON_STATE                    1681
#define IDC_PLAYBACK_MODE_PLAYBACK      1682
#define IDC_PLAYBACK_MODE_LIVE          1683
#define IDC_SET_AUDIO_PLAYER_PATH       1684
#define IDC_AUDIO_PLAYER_PATH           1685
#define IDC_SETNEXTFILENAME             1700
#define IDC_NEXT_FILE_NAME_TEXT         1701
#define IDC_CANCEL_EDIT_NEXT_FILE       1702
#define IDC_PASSWORD_TEXT               1703
#define IDC_ENTERPASSWORD               1704
#define IDC_CHANGEPASSWORD              1705
#define IDC_OLD_PASSWORD_TEXT           1706
#define IDC_NEW_PASSWORD_TEXT           1707
#define IDC_REENTER_NEW_PASSWORD_TEXT   1708
#define IDC_PORT_NUMBER                 1710
#define ID_SETTINGS_COM_CLOSE           1712
#define IDC_BAUD_300                    1714
#define IDC_BAUD_9600                   1716
#define IDC_DPI_96                      1717
#define IDC_PORT_TYPE_TCPIP             1718
#define IDC_BAUD_9602                   1719
#define IDC_DPI_120                     1720
#define IDC_PORT_TYPE_RS232             1721
#define IDC_TELNET_PORT                 1722
#define IDC_IP_ADDRESS                  1723
#define IDC_AUDIO_PATH                  1724
#define IDC_AUDIO_PORT                  1725
#define ID_LAUNCH_COM_PORT_ENUM         1726
#define IDC_LED_CAL                     1727
#define IDC_LED_X_CAL                   1728
#define IDC_LED_Y_CAL                   1729
#define ID_SETTINGS_MISC_CLOSE          1730
#define IDC_STATICREC_QUALTEXT          1735
#define IDC_STATICREC_MODE_TEXT         1736
#define IDC_STATICREC_128KBPS_TEXT      1745
#define IDC_STATICREC_96KBPS_TEXT       1750
#define IDC_STATICREC_64KBPS_TEXT       1755
#define IDC_STATICREC_32KBPS_TEXT       1756
#define IDC_STEALTH_REC_TIME_TEXT       1758
#define IDC_STEALTH_REC_NEXT_FILE_NUM   1759
#define IDC_STEALTH_NEXT_FILE_NUM_TEXT  1760
#define IDC_STEALTH_FILE_NUM_LOG_TEXT   1761
#define IDC_STEALTH_FILE_LOG_HDR_TEXT   1762
#define IDC_STEALTHREC_PLAYBACK_VOL     1763
#define IDC_STEALTHREC_DELETEFILE_NUM   1764
#define ID_CANCEL_STINGERWIN            1800
#define ID_CANCEL_EDITFILENAME          1802
#define ID_CANCEL_ENTERPASSWORD         1804
#define ID_CANCEL_PASSWORD              1806
#define ID_CANCEL_CHANGEPASSWORD        1808
#define ID_CANCEL_SPECIALSTINGERWIN     1810
#define ID_CANCEL_AUDIOSETUP            1812
#define ID_CANCEL_STEALTHRECWIN         1814
#define ID_CANCEL_PPWINDOW              1816
#define ID_CANCEL_DEBUGWIN              1818
#define ID_CANCEL_DEBUGAGCWIN           1820
#define ID_Menu                         32775
#define ID_TEST123_TEST456              32776
#define ID_PROCESS_FILE                 32777
#define ID_OPTIONS_PASSWORD             32778
#define ID_OPTIONS_CHANGEPASSWORD       32779
#define ID_Menu32780                    32780
#define ID_OPTIONS_RESTOREDEFAULTSETTINGS 32781
#define ID_PORTS                        32782
#define ID_DBM                          32783
#define ID_DBM_USEDBM                   32784
#define ID_DB_USEDBM                    32785
#define ID_PORT_TELNET                  32786
#define ID_WINDOWS                      32787
#define ID_OPTIONS_FULLSCALETONE        32788
#define ID_MISC_FULLSCALETONE           32789
#define ID_WINDOWS_SCAN                 32790
#define ID_WINDOWS_CHANNELS             32791
#define ID_WINDOWS_REMOTEPLAYER         32792
#define ID_OPTIONS_ENTERPASSWORD        32794
#define ID_OPTIONS_SPECIAL_STINGER_CMD  32795
#define ID_OPTIONS_DELETEADDRESSLIST    32797
#define ID_ADDRESSLIST_DELETECURRENTADDRESS 32798
#define ID_ADDRESSLIST_DELETEALLADDRESSES 32799
#define ID_SETSLEEPERMODE               32800
#define ID_SETSTEALTHRECORDMODE         32801
#define ID_STEALTH_REC_SPECIAL_FUNCTIONS 32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1188
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
